-- 이미 이 프로젝트에는 적용 완료됨. 다른 환경에 옮길 때만 실행.
create table if not exists public.star_universities (
  id bigint generated by default as identity primary key,
  name text not null unique,
  logo_url text,
  sort_order integer not null default 0,
  enabled boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.star_players
  add column if not exists university_id bigint references public.star_universities(id) on delete set null;

create index if not exists star_players_university_id_idx
  on public.star_players(university_id);
